from django.contrib import admin
from elearn.models import *
# Register your models here.

admin.site.register(ShotsCategory)
admin.site.register(ShotsSubCategory)
admin.site.register(Shots)
admin.site.register(Diff_Dig_Category)
admin.site.register(Diff_Dig_SubCategory)
admin.site.register(Diff_Dig)
admin.site.register(Recent_Updates_Category)
admin.site.register(Recent_Updates_SubCategory)
admin.site.register(recent_updates)
admin.site.register(WallPoster_Category)
admin.site.register(WallPoster_SubCategory)
admin.site.register(WallPosters)
admin.site.register(ICardsPDF_Category)
admin.site.register(ICardsPDF_SubCategory)
admin.site.register(ICardsPDF)
admin.site.register(ImageBank_Category)
admin.site.register(ImageBank_SubCategory)
admin.site.register(ImageBank)
admin.site.register(ICardsVideo_Category)
admin.site.register(ICardsVideo_SubCategory)
admin.site.register(ICardsVideo)
admin.site.register(ICardsAudio_Category)
admin.site.register(ICardsAudio_SubCategory)
admin.site.register(ICardsAudio)
admin.site.register(Values_Category)
admin.site.register(Values_SubCategory)
admin.site.register(Values)
admin.site.register(DailyBoostBanner)
admin.site.register(DailyBoosterQuiz)
admin.site.register(QuestionOfTheDay)
admin.site.register(QuestionBank)
admin.site.register(QuestionBank_Category)
admin.site.register(QuestionBank_SubCategory)
