# Generated by Django 3.2.5 on 2021-07-09 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shots',
            old_name='subCategory',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='shots',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.category'),
        ),
    ]
