# Generated by Django 3.2.5 on 2021-07-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_auto_20210708_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diff_dig',
            name='category',
        ),
        migrations.RemoveField(
            model_name='icardspdf',
            name='category',
        ),
        migrations.RemoveField(
            model_name='icardsvideo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='imagebank',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recent_updates',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shots',
            name='category',
        ),
        migrations.RemoveField(
            model_name='values',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wallposters',
            name='category',
        ),
    ]
