# Generated by Django 3.2.5 on 2021-07-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_auto_20210709_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBoostBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='banner/images')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBoosterQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctanswer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('timer', models.TimeField()),
                ('image', models.ImageField(upload_to='Daily/images')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('Answer1', models.CharField(max_length=200)),
                ('Answer2', models.CharField(max_length=200)),
                ('Answer3', models.CharField(max_length=200)),
                ('Answer4', models.CharField(max_length=200)),
                ('CorrectAnswer', models.CharField(max_length=200)),
                ('Explanation', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Question/images')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.dailyboostbanner')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('examtype', models.CharField(max_length=200)),
                ('numberofmcqs', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctanswer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Bank/images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_subcategory')),
            ],
        ),
    ]
