# Generated by Django 3.2.5 on 2021-07-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0008_dailyboostbanner_dailyboosterquiz_questionbank_questionbank_category_questionbank_subcategory_questi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoftheday',
            name='banner',
        ),
        migrations.AddField(
            model_name='dailyboosterquiz',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.dailyboostbanner'),
        ),
    ]
