# Generated by Django 3.2.5 on 2021-07-15 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0009_auto_20210712_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClassBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bannerimage', models.ImageField(upload_to='LiveClassBannerImage/images')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassAudio_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassNotes_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassVideo_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankPreviousQuestions_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='Videos/QuestionDiscussion/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyboosterquiz',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='dailyboosterquiz',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='correctanswer',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='image',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='question',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='exam_mode',
            field=models.CharField(default='Q_BankMode', max_length=200),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='level',
            field=models.CharField(default='Easy', max_length=200),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_subcategory'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_category'),
        ),
        migrations.CreateModel(
            name='QuestionBankTestMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('examtype', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctanswer', models.CharField(max_length=200)),
                ('timer', models.IntegerField()),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankQuizTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('timer', models.TimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankPreviousQuestions_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbankpreviousquestions_category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankPreviousQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='Notes/QuestionBankPreviousQuestions/')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbankpreviousquestions_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('examtype', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctanswer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='Q_BANK_MODE/images')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassVideo_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassvideo_category')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='Videos/PrimeClass/')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassvideo_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassNotes_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassnotes_category')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='Notes/PrimeClass/')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassnotes_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassAudio_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassaudio_category')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeClassAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='Audios/PrimeClass/')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.primeclassaudio_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.liveclass_category')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.liveclassbannerimage')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.liveclass_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBoosterQuizTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timer', models.TimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBoosterMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.IntegerField()),
                ('no_of_mcq', models.CharField(max_length=200)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.dailyboostbanner')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBoosterCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.AddField(
            model_name='dailyboosterquiz',
            name='dailyboostdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.dailyboostermain'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user'),
        ),
    ]
