# Generated by Django 3.2.5 on 2021-07-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0010_auto_20210714_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbankcompleted',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='questionbankcompleted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionbankquiztimer',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='questionbankquiztimer',
            name='user',
        ),
        migrations.AddField(
            model_name='questionbankcompleted',
            name='question_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank'),
        ),
        migrations.AddField(
            model_name='questionbankquiztimer',
            name='question_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.questionbank'),
        ),
    ]
