# Generated by Django 3.2.5 on 2021-07-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0012_auto_20210715_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
