# Generated by Django 3.2.5 on 2021-07-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0013_user_is_blocked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Registration',
        ),
    ]
