# Generated by Django 3.2.5 on 2021-07-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0019_icardspastpaper_icardspastpaper_category_icardspastpaper_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyboostermain',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
