# Generated by Django 3.2.5 on 2021-07-18 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0020_dailyboostermain_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Videos/Discussion/')),
                ('question', models.CharField(max_length=200)),
                ('question_time', models.TimeField()),
                ('notes', models.FileField(upload_to='notes/Discussion/')),
                ('image', models.ImageField(upload_to='Discussion/images')),
                ('bookmark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDiscussionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='GroupDiscussionAdmin/images')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('no_of_mcq', models.CharField(max_length=200)),
                ('timer', models.CharField(max_length=200)),
                ('result_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.test_category')),
            ],
        ),
        migrations.CreateModel(
            name='TestDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctAnswer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='TestDiscussion/images')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('not_viewed', models.IntegerField()),
                ('test_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.test_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctanswer', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='TestQuestions/images')),
                ('test_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.test_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Videos/TestQuestionDiscussion/')),
                ('question', models.CharField(max_length=200)),
                ('question_time', models.TimeField()),
                ('image', models.ImageField(upload_to='TestQuestionDiscussion/images')),
                ('notes', models.FileField(upload_to='notes/TestQuestionDiscussion/')),
                ('bookmark', models.BooleanField(default=False)),
                ('test_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.test_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('Test_SubCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.test_subcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDiscussionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('files', models.FileField(upload_to='files/GroupDiscussionUser/')),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correctAnswer', models.CharField(max_length=200)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.groupdiscussionadmin')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBoosterBookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_status', models.BooleanField(default=False)),
                ('DailyBoosterMain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.dailyboostermain')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.user')),
            ],
        ),
    ]
