# Generated by Django 3.2.3 on 2021-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0022_alter_dailyboosterbookmark_dailyboostermain'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbanktestmode',
            name='explanation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questionbanktestmode',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='Q_BANK_MODE/images'),
        ),
    ]
